name: "Monkey Run Tests"
on: [push]

jobs:
  
  ## Basic
  test-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Basic Success
        conclusion: success
  
  test-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Basic Success
        conclusion: success
  
  test-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Basic Success
        conclusion: success            

  
